// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnkM5cSLkciro0b5aBwcOIOyeuXtVt60',
    appId: '1:392790768425:web:3a3c213938761480e11538',
    messagingSenderId: '392790768425',
    projectId: 'iti-project2-andrewbekhiet',
    authDomain: 'iti-project2-andrewbekhiet.firebaseapp.com',
    storageBucket: 'iti-project2-andrewbekhiet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAebjdzncqS3fneb7BvtFveR7Vx38sn-Q',
    appId: '1:392790768425:android:6fe0a88160d7d6e3e11538',
    messagingSenderId: '392790768425',
    projectId: 'iti-project2-andrewbekhiet',
    storageBucket: 'iti-project2-andrewbekhiet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrESZ3RRr1EnS5ggC51lckchX7P48gkTA',
    appId: '1:392790768425:ios:06b4b58dec065863e11538',
    messagingSenderId: '392790768425',
    projectId: 'iti-project2-andrewbekhiet',
    storageBucket: 'iti-project2-andrewbekhiet.firebasestorage.app',
    iosBundleId: 'com.AndroidQuartz.marquee',
  );
}
